window.sampleReport = {
  reportName: "理性投资系统日报",
  date: "2026-03-13",
  generatedAt: "2026-03-13 17:40",
  philosophy:
    "# 理性投资系统\n\n1. 做简单高胜率的事。\n2. 暴跌超15%后观察流动性风险带来的错杀机会。\n3. 重大变化与风险失控时果断卖出。\n4. 顺风期充分被认知后逐步减仓。",
  feedbackInbox:
    "# 心得增量收件箱\n\n- 未来你在飞书里补充的新心得，可以整理后并入主规则库。",
  watchlist: [
    { ticker: "0700.HK", name: "腾讯控股", sector: "互联网/科技 (中国)", market: "hongkong", enabled: true },
    { ticker: "AAPL", name: "Apple", sector: "互联网/科技 (美国)", market: "us", enabled: true },
    { ticker: "NVDA", name: "NVIDIA", sector: "制造/电子", market: "us", enabled: true },
  ],
  benchmarks: {
    us: { score: 62, label: "中性偏强" },
    hongkong: { score: 57, label: "中性偏强" },
    china: { score: 48, label: "中性" },
  },
  summary: {
    buyCount: 1,
    holdCount: 1,
    waitCount: 1,
    sellCount: 0,
    total: 3,
  },
  decisions: [
    {
      ticker: "NVDA",
      name: "NVIDIA",
      sector: "制造/电子",
      market: "us",
      decision: "BUY",
      confidence: 82,
      score: 78,
      price: 938.2,
      change1d: 0.021,
      change5d: 0.067,
      benchmark: "中性偏强",
      summary: "技术面出现较完整共振，可考虑分批买入或调高观察级别。",
      keyFactors: ["价格站上 MA20", "MA20 位于 MA60 上方，中期结构偏多", "MACD 柱体转正，动量改善"],
      warnings: ["RSI 偏热，注意顺风期减仓"],
      questions: [
        { question: "趋势是否站上中期均线？", answer: "是", note: "收盘 $938.20，MA20 $902.10，MA60 $861.70" },
        { question: "技术指标是否出现共振？", answer: "是", note: "MACD柱 +2.18，RSI14 64.8" },
      ],
      technical: {
        ma5: 925.3,
        ma20: 902.1,
        ma60: 861.7,
        rsi14: 64.8,
        macdHist: 2.18,
        k: 69.4,
        d: 63.1,
        bollUpper: 951.6,
        bollLower: 852.4,
        volumeRatio: 1.24,
        drawdown60: -0.082,
      },
    },
    {
      ticker: "0700.HK",
      name: "腾讯控股",
      sector: "互联网/科技 (中国)",
      market: "hongkong",
      decision: "HOLD",
      confidence: 60,
      score: 63,
      price: 318.6,
      change1d: 0.008,
      change5d: 0.012,
      benchmark: "中性偏强",
      summary: "结构没有破坏，继续持有并观察关键均线与量价配合。",
      keyFactors: ["价格站上 MA20", "KDJ 保持金叉或强势钝化"],
      warnings: ["MACD 柱体为负，动量承压"],
      questions: [
        { question: "趋势是否站上中期均线？", answer: "是", note: "收盘 $318.60，MA20 $312.50，MA60 $305.40" },
        { question: "是否触发风险退出信号？", answer: "否", note: "跌破均线且动量转负时优先保护资金" },
      ],
      technical: {
        ma5: 317.9,
        ma20: 312.5,
        ma60: 305.4,
        rsi14: 55.4,
        macdHist: -0.41,
        k: 58.8,
        d: 55.2,
        bollUpper: 326.5,
        bollLower: 298.1,
        volumeRatio: 0.96,
        drawdown60: -0.111,
      },
    },
    {
      ticker: "AAPL",
      name: "Apple",
      sector: "互联网/科技 (美国)",
      market: "us",
      decision: "WAIT",
      confidence: 52,
      score: 46,
      price: 213.4,
      change1d: -0.007,
      change5d: -0.019,
      benchmark: "中性偏强",
      summary: "信号不够统一，先观望，避免情绪化操作。",
      keyFactors: ["市场环境 中性偏强，对多头更友好"],
      warnings: ["价格跌破 MA20", "MACD 柱体为负，动量承压"],
      questions: [
        { question: "趋势是否站上中期均线？", answer: "否", note: "收盘 $213.40，MA20 $216.90，MA60 $209.80" },
        { question: "市场环境是否支持？", answer: "是", note: "对应市场风格：中性偏强 (62)" },
      ],
      technical: {
        ma5: 214.2,
        ma20: 216.9,
        ma60: 209.8,
        rsi14: 46.2,
        macdHist: -0.86,
        k: 45.3,
        d: 49.6,
        bollUpper: 222.8,
        bollLower: 208.7,
        volumeRatio: 1.05,
        drawdown60: -0.095,
      },
    },
  ],
  meta: {
    philosophyPath: "config/philosophy.md",
    watchlistPath: "config/watchlist.json",
    feedbackInboxPath: "config/feedback_inbox.md",
    companyProfilesPath: "config/company_profiles.json",
  },
};
